debugging

diff --git a/.github/workflows/quarto-build.yml b/.github/workflows/quarto-build.yml
--- a/.github/workflows/quarto-build.yml
+++ b/.github/workflows/quarto-build.yml
@@ -144,7 +144,7 @@ jobs:
             libtiff5-dev \
             libxml2-dev \
             pango1.0-tools
-            
+
           # Reinstall font related libraries and inkscape.
           echo "🔄 Reinstalling font libraries and Inkscape..."
           sudo apt-get install --reinstall -y libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libfontconfig1 libfreetype6 inkscape
@@ -188,13 +188,18 @@ jobs:
       - name: Check Inkscape version
         run: inkscape --version
 
-      - name: 🧪 Test Inkscape Conversion
-        shell: bash
-        run: |
-          echo '<svg xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="40"/></svg>' > test.svg
-          inkscape test.svg --export-type=pdf --export-filename=test.pdf
-          ls -lh test.pdf || echo "❌ Inkscape export failed"
-          
+
+      # - name: 🧪 Test Inkscape Conversion
+      #   shell: bash
+      #   run: |
+      #     echo '<svg xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="40"/></svg>' > test.svg
+      #     inkscape test.svg --export-type=pdf --export-filename=test.pdf
+      #     ls -lh test.pdf || echo "❌ Inkscape export failed"
+
+
+
+
+
       - name: 📦 Install & Update TeX Live 
         uses: teatimeguest/setup-texlive-action@v3
         with:
